# Pipeline para aplicação Java 17 com Maven
name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [clienteservice, pedidoservice, middleware]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn clean compile

      - name: Run tests for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn test

      - name: Package ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn package -DskipTests

      - name: Upload artifact for ${{ matrix.service }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.service }}-jar
          path: ${{ matrix.service }}/target/*.jar
          retention-days: 30

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Run integration tests
        run: |
          cd middleware
          mvn test -Dtest=MiddlewareIntegrationTest